services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago # Change to your timezone (e.g., America/Chicago)
    volumes:
      - /opt/docker/media/config/prowlarr:/config
      - /mnt/downloads:/downloads # Optional: for consistent path mapping
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/media/config/radarr:/config
      - /mnt/windows_media/movie:/movies # Movies library
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/media/config/sonarr:/config
      - /mnt/windows_media/series:/tv # TV shows library
      - /mnt/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host # Simplifies network setup for Plex discovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      # Get a claim token from www.plex.tv just before starting the container
      #- PLEX_CLAIM="insert_your_claim_token_here" 
    volumes:
      - /opt/docker/media/config/plex:/config
      - /mnt/windows_media/movie:/movies
      - /mnt/windows_media/series:/tv
      - /opt/docker/media/transcode:/transcode # Optional: path for optimized transcoding
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080" # Web UI
      - "6881:6881" # Torrent port (TCP)
      - "6881:6881/udp" # Torrent port (UDP)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
      - /opt/docker/media/config/qbittorrent:/config
      - /mnt/downloads:/downloads
    restart: unless-stopped


  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    # Updates the other containers automatically
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      # Optional: set a shorter update check time, e.g., daily (86400 seconds)
      # - WATCHTOWER_POLL_INTERVAL=86400 
    volumes:
      # Mount the Docker socket to allow Watchtower to manage containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - /opt/docker/media/config/jellyseerr:/app/config
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    volumes:
      - /var/lib/flaresolver:/config
    restart: unless-stopped
